name = "spinitron-mobile-app-cloudflare-worker"
main = "cloudflare-worker/main.js"
compatibility_date = "2025-09-21"

# Set to skip dependency install during deploy
[vars]
SKIP_DEPENDENCY_INSTALL = true

# [build]
# command = ""

# [triggers]
# crons = []

# [env.production]
# Add production-specific settings here

# route = { pattern = "example.org/*", zone_name = "example.org" }
# kv_namespaces = [{ binding = "<MY_NAMESPACE>", id = "<KV_ID>" }]
