name = "spinitron-mobile-app-cloudflare-worker"
main = "cloudflare-worker/main.js"
compatibility_date = "2025-09-21"
no_bundle = true

[build]
cwd = "cloudflare-worker"
watch_dir = "cloudflare-worker"

#### Cloudflare Workers UI settings ####
# deploy command: npx wrangler deploy main.js --no-bundle
# path: cloudflare-worker
