name: update
on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    needs: set-variants
    strategy:
      matrix:
        variant: ${{ fromJson(needs.set-variants.outputs.variants) }} # e.g. "variants/acme"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Apply variant config
        run: cat ${{ matrix.variant }}/app.config.ts > app.config.ts

      - name: Install dependencies
        run: npm ci

      - name: Publish update
        run: eas update --auto

  set-variants:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.set-variants.outputs.variants }}
    steps:
      - name: Get variants
        id: set-variants
        run: echo "::set-output name=variants::$(find variants -mindepth 1 -maxdepth 1 -type d ! -name 'acme' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
